chewing/chewing-editor

CMakeLists.txt
src/main.cpp
ts/ts.qrc

Before this PR, the translation files (files with extension `.qm`) were separated from the executable file.
It is troublesome to distribute the translation files to users, you will need a installer/packager to achieve that.
To overcome this minor inconvenience, I suggest to embed these translation files directly into the executable file.

Embed Qt translation files into chewing-editor binary

---

CMakeLists.txt

When double-click (to execute) `chewing-editor.exe`, there is a ugly console window, this patch take care (hide) of it:
Update: This issue exists solely on windows platform.

Hide console window on Windows

---

README.md

We depends on `libchewing >= 0.4.0` since closing issue https://github.com/chewing/chewing-editor/issues/26 .
Update the dependency in `README.md`.

Update libchewing Requirement in README.md

---

ts/chewing-editor_en_US.ts
ts/chewing-editor_zh_TW.ts

After we added the shortcut on the menu items (at https://github.com/chewing/chewing-editor/commit/ac937289c37ea89dd9c4309330d802ffdbb69983), we have to separate menu items from dialog titles to fix https://github.com/chewing/chewing-editor/issues/76.

Fix menu translation

---

.gitignore
CMakeLists.txt

If build system has `gzip`, use it to compress the manpage.
This will close #51.

Use gzip to compress the manpage

---

CMakeLists.txt

This allow building process to run more smoothly (especially for building AUR package).

Allow gzip to always overwrite output file.

---

src/view/Notification.cpp
ts/chewing-editor_en_US.ts
ts/chewing-editor_zh_TW.ts

Close #95.
BTW, `edit` is vanished but I still update it's translation to `編輯`.

Update translation and quote the filename while importing/exporting

---

src/view/UserphraseDialog.cpp

Ideally `setFocus` should be placed at `UserphraseDialog` ctor, but I'm too lazy to refactor the whole class...

Grab focus to phrase input widget on dialog open.

---

src/ui/ChewingEditor.ui

This will close #129.
Before:
After:
ref: http://www.slideshare.net/qtbynokia/how-to-make-your-qt-app-look-native
Notice that `chewing-editor` only can be changed in other way, I'll send a patch later.

Make menu more natively on Mac OS X

---

src/view/ChewingEditor.cpp
src/view/ChewingEditor.h

....for the following actions: Add, Remove,Modify, Refresh, Import, Export. Quit
|Action|Keys| Test in linux|
| ------------- |:-------------:| -----:|
|Add|QKeySequence::New|CTRL+N|
|Remove|QKeySequence::Delete|Delete|
|Modify|Qt::Key_Return|Enter|
|Refresh|Qt::CTRL + Qt::Key_R|CTRL+R|
|Import|Qt::CTRL + Qt::Key_I|CTRL+I|
|Export|Qt::CTRL + Qt::Key_E|CTRL+E|
|Quit|QKeySequence::Quit|CTRL+Q|
doc: https://doc.qt.io/qt-5/qkeysequence.html#StandardKey-enum

Add shortcuts

---

.gitignore

On OS X, cmake will generate `chewing-editor.dSYM` folder to place information for the executable.

Add chewing-editor.dSYM into .gitignore for OS X builds

---

.gitignore

On OS X, the filesystem is case-insensitive, so we need to care about the `cmake/` directory after https://github.com/chewing/chewing-editor/pull/130.

Fix gitignore for cmake/ on OS X

---

src/model/UserphraseModel.cpp
src/model/UserphraseModel.h

Automatically change the character from "一" to "ㄧ"
Add refresh() function in the add function to reduce the problem of wrong bopomofo

Solve character ambiguity and refresh()

---

CMakeLists.txt
chewing-editor.desktop.in

It would be best if we provided lower resolutions icons, but my DE (cinnamon) can do the downsize (256 to lower res) perfectly.

Installation improvements

---

src/model/UserphraseModel.cpp
src/model/UserphraseModel.h
src/view/UserphraseView.cpp
src/view/UserphraseView.h

This will close #75  #109 
When the "add" step is failed, the function will re-add the original phrase back.
This is my first pull request, wherever I can improve, please tell me.

 Phrase can be preserved when the "add" step in "modify" is failed.

---

src/model/UserphraseModel.cpp
src/model/UserphraseModel.h
src/view/ChewingEditor.cpp
src/view/Notification.cpp
src/view/Notification.h
ts/chewing-editor_en_US.ts
ts/chewing-editor_zh_TW.ts

Close #160
When user add phrase fail, there will be a notification tell user the movement is failed:
(The phrase still add in editor because of the auto-learning function in libchewing)
Does the notification need to show the content of the phrase add failed?

Notify user when add phrase failed

---

src/view/ChewingEditor.cpp

fix, or probably workaround for issue #49.
not sure if this happen only on Ubuntu or other distro are also having the same issue, but not using native file dialog seems to fix the problem in Ubuntu.
References:
https://bugreports.qt.io/browse/QTBUG-38985,
http://forum.qt.io/topic/41356/qfiledialog-signal-fileselected-is-triggered-twice-for-one-user-choice-changed-in-recent-qt/2

Fix to show correct number of imported phrases

---

src/model/UserphraseModel.cpp
src/model/UserphraseModel.h
src/ui/ChewingEditor.ui
src/view/ChewingEditor.cpp
src/view/ChewingEditor.h
src/view/Notification.cpp
src/view/Notification.h
ts/chewing-editor_en_US.ts
ts/chewing-editor_zh_TW.ts

The undo function only supports reverting of phrase deletions.
It supports multiple deletions but users have to revert them one by one.
I edited the translation file for the new feature, and updated several line numbers to match
the changing of ui and cpp files.
Is there any missing place, please tell me and I will improve it.
Thanks!
Resolves: #133

Undo function for phrase deletions and translation for undo function

---

chewing-editor.desktop.in

Version value should be 1.0, not project version:
See https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html
Note that Version is not a required key and can be removed instead.
Close #180.

fix invalid Version value in desktop file.

---

.travis.yml

* Fix TravisCI build fail
* Opt-in to use Ubuntu Trusty as building platform, see: https://docs.travis-ci.com/user/trusty-ci-environment
* Enable building with ccache on TravisCI, see: https://docs.travis-ci.com/user/caching/#ccache-cache
* By default, the following packages are already newest in the Trusty image: cmake-data, pkg-config. So there is no need to install them manually.

Fix TravisCI build failing

---

src/view/ChewingEditor.cpp

I found that it can't show the correct dialogType value, because it print log before changed the value.

Fix dialogType display wrong value in debug mode

---

src/model/UserphraseModel.cpp

Replacing `一` into `ㄧ` and `丫` into `ㄚ` correctly.

Fix #169 to catch the ambiguity word correctly

---

.travis.yml
CMakeLists.txt

Fixed #203. Fixed #215.
Since we only support Qt5 now, we can use `find_package(Qt5LinguistTools)` to handle `lupdate` and `lrelease` without `qtchooser`. This could fix #203, and this must fix #215, too.

Use Qt5LinguistTools instead of using qtchooser (with linguist tools)

---

src/view/ChewingEditor.cpp

Fixed #192 .
Checking the selection phrases instead of only checking if there is no phrase.
I squashed my commit, PR #200.

Fix remove phrase incorrect behavior

---

CMakeLists.txt

By default gzip embeds the last modified time of the original file,
which makes the compressed file unreproducible. `-n` prevents that.

Make man pages reproducible

---

.github/workflows/ci.yml
CMakeLists.txt
src/model/UserphraseModel.cpp
src/view/ChewingEditor.cpp

Clean up Qt-related warnings

---

.gitignore
CMakeLists.txt

References
- https://bugzilla.redhat.com/show_bug.cgi?id=2380494
- https://fedoraproject.org/wiki/Changes/CMake4.0

build: add upper bound to cmake_minimum_required version
